name: Analyze Release
description: Analyzes conventional commits and outputs bump and next version.
outputs:
  last_tag:
    description: Último tag encontrado
    value: ${{ steps.get_tag.outputs.last_tag }}
  bump:
    description: Calculated bump (patch, minor, major)
    value: ${{ steps.bump.outputs.bump }}
  next_version:
    description: Next calculated semver version
    value: ${{ steps.version.outputs.next_version }}

runs:
  using: "composite"
  steps:
    - name: Fetch tags
      run: git fetch --prune --tags
      shell: bash

    - name: Get latest tag
      id: get_tag
      run: |
        TAG=$(git describe --tags --abbrev=0 || echo "0.0.0")
        echo "last_tag=$TAG" >> $GITHUB_OUTPUT
      shell: bash

    - name: Print commits
      run: git log ${{ steps.get_tag.outputs.last_tag }}..HEAD --pretty=format:"%H %s"
      shell: bash

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Run analyze-bump.js
      id: bump
      run: |
        BUMP=$(FROM_TAG="${{ steps.get_tag.outputs.last_tag }}" node ${{ github.action_path }}/analyze-bump.js | grep '^Determined bump' | sed 's/^Determined bump: //')
        echo "bump=$BUMP" >> $GITHUB_OUTPUT
      shell: bash

    - name: Calculate next version
      id: version
      if: steps.bump.outputs.bump != ''
      run: |
        npm install semver
        VERSION=$(npx semver "${{ steps.get_tag.outputs.last_tag }}" -i "${{ steps.bump.outputs.bump }}")
        echo "next_version=$VERSION" >> $GITHUB_OUTPUT
      shell: bash