name: Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      prereleaseTag:
        description: 'Nombre del prerelease tag (ej: alpha, beta)'
        required: false
        default: 'alpha'

jobs:
  release:
    name: Build&Release
    uses: Parsimotion/public-workflows/.github/workflows/release.yml@main
    with:
      prereleaseTag: ${{ inputs.prereleaseTag }}
      build: false
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      issues: write